
var kzg = (() => {
  var _scriptDir = import.meta.url;
  
  return (
function(moduleArg = {}) {

var b=moduleArg,n,q;b.ready=new Promise((a,d)=>{n=a;q=d});var u=Object.assign({},b),v="";"undefined"!=typeof document&&document.currentScript&&(v=document.currentScript.src);_scriptDir&&(v=_scriptDir);v.startsWith("blob:")?v="":v=v.substr(0,v.replace(/[?#].*/,"").lastIndexOf("/")+1);var x=b.printErr||console.error.bind(console);Object.assign(b,u);u=null;var y;b.wasmBinary&&(y=b.wasmBinary);"object"!=typeof WebAssembly&&z("no native wasm support detected");var A,B=!1,C,D;
function F(){var a=A.buffer;b.HEAP8=C=new Int8Array(a);b.HEAP16=new Int16Array(a);b.HEAPU8=D=new Uint8Array(a);b.HEAPU16=new Uint16Array(a);b.HEAP32=new Int32Array(a);b.HEAPU32=new Uint32Array(a);b.HEAPF32=new Float32Array(a);b.HEAPF64=new Float64Array(a)}var G=[],H=[],I=[];function aa(){var a=b.preRun.shift();G.unshift(a)}var J=0,K=null,L=null;function z(a){b.onAbort?.(a);a="Aborted("+a+")";x(a);B=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");q(a);throw a;}
var M=a=>a.startsWith("data:application/octet-stream;base64,"),N;if(b.locateFile){if(N="kzg.wasm",!M(N)){var O=N;N=b.locateFile?b.locateFile(O,v):v+O}}else N=(new URL("kzg.wasm",import.meta.url)).href;function P(a){if(a==N&&y)return new Uint8Array(y);throw"both async and sync fetching of the wasm failed";}
function ba(a){return y||"function"!=typeof fetch?Promise.resolve().then(()=>P(a)):fetch(a,{credentials:"same-origin"}).then(d=>{if(!d.ok)throw`failed to load wasm binary file at '${a}'`;return d.arrayBuffer()}).catch(()=>P(a))}function Q(a,d,c){return ba(a).then(e=>WebAssembly.instantiate(e,d)).then(e=>e).then(c,e=>{x(`failed to asynchronously prepare wasm: ${e}`);z(e)})}
function ca(a,d){var c=N;return y||"function"!=typeof WebAssembly.instantiateStreaming||M(c)||"function"!=typeof fetch?Q(c,a,d):fetch(c,{credentials:"same-origin"}).then(e=>WebAssembly.instantiateStreaming(e,a).then(d,function(f){x(`wasm streaming compile failed: ${f}`);x("falling back to ArrayBuffer instantiation");return Q(c,a,d)}))}
var R=a=>{for(;0<a.length;)a.shift()(b)},S="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,T=a=>{if(a){for(var d=D,c=a+NaN,e=a;d[e]&&!(e>=c);)++e;if(16<e-a&&d.buffer&&S)a=S.decode(d.subarray(a,e));else{for(c="";a<e;){var f=d[a++];if(f&128){var l=d[a++]&63;if(192==(f&224))c+=String.fromCharCode((f&31)<<6|l);else{var r=d[a++]&63;f=224==(f&240)?(f&15)<<12|l<<6|r:(f&7)<<18|l<<12|r<<6|d[a++]&63;65536>f?c+=String.fromCharCode(f):(f-=65536,c+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else c+=
String.fromCharCode(f)}a=c}}else a="";return a},da=(a,d,c,e)=>{var f={string:h=>{var p=0;if(null!==h&&void 0!==h&&0!==h){for(var g=p=0;g<h.length;++g){var m=h.charCodeAt(g);127>=m?p++:2047>=m?p+=2:55296<=m&&57343>=m?(p+=4,++g):p+=3}var t=p+1;g=p=U(t);m=D;if(0<t){t=g+t-1;for(var E=0;E<h.length;++E){var k=h.charCodeAt(E);if(55296<=k&&57343>=k){var ea=h.charCodeAt(++E);k=65536+((k&1023)<<10)|ea&1023}if(127>=k){if(g>=t)break;m[g++]=k}else{if(2047>=k){if(g+1>=t)break;m[g++]=192|k>>6}else{if(65535>=k){if(g+
2>=t)break;m[g++]=224|k>>12}else{if(g+3>=t)break;m[g++]=240|k>>18;m[g++]=128|k>>12&63}m[g++]=128|k>>6&63}m[g++]=128|k&63}}m[g]=0}}return p},array:h=>{var p=U(h.length);C.set(h,p);return p}};a=b["_"+a];var l=[],r=0;if(e)for(var w=0;w<e.length;w++){var X=f[c[w]];X?(0===r&&(r=V()),l[w]=X(e[w])):l[w]=e[w]}c=a.apply(null,l);return c=function(h){0!==r&&W(r);return"string"===d?T(h):"boolean"===d?!!h:h}(c)},fa={c:(a,d,c,e)=>{z(`Assertion failed: ${T(a)}, at: `+[d?T(d):"unknown filename",c,e?T(e):"unknown function"])},
b:(a,d,c)=>D.copyWithin(a,d,d+c),a:a=>{var d=D.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var e=d*(1+.2/c);e=Math.min(e,a+100663296);var f=Math;e=Math.max(a,e);a:{f=(f.min.call(f,2147483648,e+(65536-e%65536)%65536)-A.buffer.byteLength+65535)/65536;try{A.grow(f);F();var l=1;break a}catch(r){}l=void 0}if(l)return!0}return!1}},Y=function(){function a(c){Y=c.exports;A=Y.d;F();H.unshift(Y.e);J--;b.monitorRunDependencies?.(J);0==J&&(null!==K&&(clearInterval(K),K=null),L&&(c=L,L=null,
c()));return Y}var d={a:fa};J++;b.monitorRunDependencies?.(J);if(b.instantiateWasm)try{return b.instantiateWasm(d,a)}catch(c){x(`Module.instantiateWasm callback failed with error: ${c}`),q(c)}ca(d,function(c){a(c.instance)}).catch(q);return{}}();b._load_trusted_setup_from_wasm=(a,d,c,e)=>(b._load_trusted_setup_from_wasm=Y.f)(a,d,c,e);b._free_trusted_setup_wasm=()=>(b._free_trusted_setup_wasm=Y.g)();b._blob_to_kzg_commitment_wasm=a=>(b._blob_to_kzg_commitment_wasm=Y.h)(a);
b._compute_blob_kzg_proof_wasm=(a,d)=>(b._compute_blob_kzg_proof_wasm=Y.i)(a,d);b._verify_blob_kzg_proof_wasm=(a,d,c)=>(b._verify_blob_kzg_proof_wasm=Y.j)(a,d,c);b._verify_kzg_proof_wasm=(a,d,c,e)=>(b._verify_kzg_proof_wasm=Y.k)(a,d,c,e);var V=()=>(V=Y.m)(),W=a=>(W=Y.n)(a),U=a=>(U=Y.o)(a);b.cwrap=(a,d,c,e)=>{var f=!c||c.every(l=>"number"===l||"boolean"===l);return"string"!==d&&f&&!e?b["_"+a]:function(){return da(a,d,c,arguments)}};var Z;L=function ha(){Z||ia();Z||(L=ha)};
function ia(){function a(){if(!Z&&(Z=!0,b.calledRun=!0,!B)){R(H);n(b);if(b.onRuntimeInitialized)b.onRuntimeInitialized();if(b.postRun)for("function"==typeof b.postRun&&(b.postRun=[b.postRun]);b.postRun.length;){var d=b.postRun.shift();I.unshift(d)}R(I)}}if(!(0<J)){if(b.preRun)for("function"==typeof b.preRun&&(b.preRun=[b.preRun]);b.preRun.length;)aa();R(G);0<J||(b.setStatus?(b.setStatus("Running..."),setTimeout(function(){setTimeout(function(){b.setStatus("")},1);a()},1)):a())}}
if(b.preInit)for("function"==typeof b.preInit&&(b.preInit=[b.preInit]);0<b.preInit.length;)b.preInit.pop()();ia();


  return moduleArg.ready
}
);
})();
export default kzg;